### ISSUE TITLE
Issue on saving the output

### ISSUE THREAD

**Issue by theMIK27** [mtacnet/json-merger#1]
Hello,

After selecting 1000 json files the choose files button still shows the number of json files selected. But there is no way to download the output. Can you please address this issue?

Thanks.

**Comment by mtacnet** [comment]
Hi 👋🏻 

The download is supposed to be automatic after selecting the files.

If the files are very large I imagine it may take a little time (the processing time) before the download takes place.

I tried to reproduce your problem with at least 1000 files and I did not encounter any problems, however my files do not contain a lot of data.

Are you still having the problem ?

**Comment by mtacnet** [comment]
@theMIK27 Did you read my previous message ? 

Can you detail your manipulation and / or do you still encounter the problem ?

**Comment by theMIK27** [comment]
Hey, 

Sorry for the late reply. I did try, but the total volume of that 1000 files is a little more than 80 GB, and it takes a whole lot of time. I waited around 20-25 minutes but never got the output. 

Thanks.
